spring.application.name=CafeDior
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${SERVER_PORT}

jwt.access.secret=${JWT_ACCESS}
jwt.access.expiration=${JWT_ACC_EXP}
jwt.refresh.secret=${JWT_REFRESH}
jwt.refresh.expiration=${JWT_REF_EXP}

springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=com.lemurybiznesu.backend

app.images.path=D:/Projekty/CafeDior/backend/images

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB